server:
  forward-headers-strategy: framework   # ★ 루트 레벨

spring:
  profiles:
    active: db
  
  data:
    redis:
      host: redis
      port: 6379

# Swagger(OpenAPI) springdoc 설정
springdoc:
  api-docs:
    path: /api-docs   # OpenAPI 명세 경로 (기본: /v3/api-docs)
  swagger-ui:
    path: /swagger-ui # Swagger UI 경로 (기본: /swagger-ui.html)

#구글 로그인
google:
  oauth:
    client-ids:
      - 67500785353-oq4u26r3uek1s7b569sfr52sjkvj7j36.apps.googleusercontent.com

#aws
aws:
  accessKey: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_ACCESS_KEY}

s3:
  bucket: ${S3_BUCKET_NAME}
  region: ${AWS_REGION}

#JWT
jwt:
  issuer: acm-server
  secret: ${JWT_SECRET}
  access-token-validity-seconds: 900        # 15분
  refresh-token-validity-seconds: 1209600   # 14일

encryption:
  aes-key: ${ENCRYPTION_AES_KEY}


